"""Add offensive security models

Revision ID: 45ab3695d0c3
Revises: add_persistence_models
Create Date: 2026-01-27 14:57:06.848786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45ab3695d0c3'
down_revision: Union[str, None] = 'add_persistence_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_framework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_framework_id'), 'compliance_framework', ['id'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_member_id'), 'team_member', ['id'], unique=False)
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_id'), 'user_activity', ['id'], unique=False)
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('targets', sa.JSON(), nullable=True),
    sa.Column('chain_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', name='campaignstatusenum'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_id'), 'campaign', ['id'], unique=False)
    op.create_table('compliance_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=True),
    sa.Column('control_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_framework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_control_id'), 'compliance_control', ['id'], unique=False)
    op.create_table('payload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payload_type', sa.Enum('REVERSE_SHELL', 'TROJAN', 'RAT', 'DLL_HIJACK', 'PROCESS_INJECTION', 'FILELESS', name='payloadtypeenum'), nullable=False),
    sa.Column('platform', sa.Enum('WINDOWS', 'LINUX', 'MACOS', 'ANDROID', name='platformenum'), nullable=False),
    sa.Column('language', sa.Enum('PYTHON', 'POWERSHELL', 'BASH', 'C', 'CPP', 'CSHARP', 'GO', name='languageenum'), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('obfuscated_code', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('embedded_file_path', sa.String(length=500), nullable=True),
    sa.Column('lhost', sa.String(length=100), nullable=True),
    sa.Column('lport', sa.Integer(), nullable=True),
    sa.Column('evasion_techniques', sa.JSON(), nullable=True),
    sa.Column('detection_rate', sa.Float(), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payload_id'), 'payload', ['id'], unique=False)
    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('hash_value', sa.Text(), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('protocol', sa.String(length=50), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('source_tool', sa.String(length=100), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_id'), 'credential', ['id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.Enum('EXECUTIVE', 'TECHNICAL', 'COMPLIANCE', name='reporttypeenum'), nullable=True),
    sa.Column('format', sa.Enum('JSON', 'MARKDOWN', 'PDF', 'HTML', name='reportformatenum'), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    op.create_table('se_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_email', sa.String(length=255), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('target_company', sa.String(length=255), nullable=True),
    sa.Column('target_info', sa.JSON(), nullable=True),
    sa.Column('phishing_template', sa.Text(), nullable=True),
    sa.Column('payload_id', sa.Integer(), nullable=True),
    sa.Column('tracking_link', sa.String(length=500), nullable=True),
    sa.Column('email_opened', sa.Boolean(), nullable=True),
    sa.Column('link_clicked', sa.Boolean(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('credentials_captured', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'PAUSED', 'COMPLETED', name='sestatusenum'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payload_id'], ['payload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_se_campaign_id'), 'se_campaign', ['id'], unique=False)
    op.create_table('compliance_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=True),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['compliance_control.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_mapping_id'), 'compliance_mapping', ['id'], unique=False)
    op.drop_index(op.f('ix_malware_analysis_id'), table_name='malware_analysis')
    op.drop_table('malware_analysis')
    op.add_column('finding', sa.Column('status', sa.Enum('NEW', 'CONFIRMED', 'FALSE_POSITIVE', 'FIXED', 'IGNORED', name='statusenum'), nullable=True))
    op.add_column('finding', sa.Column('target', sa.String(length=255), nullable=True))
    op.add_column('finding', sa.Column('tool', sa.String(length=100), nullable=True))
    op.add_column('finding', sa.Column('cve_id', sa.String(length=50), nullable=True))
    op.add_column('finding', sa.Column('cvss_score', sa.String(length=10), nullable=True))
    op.add_column('finding', sa.Column('remediation', sa.Text(), nullable=True))
    op.add_column('finding', sa.Column('references', sa.Text(), nullable=True))
    op.add_column('finding', sa.Column('campaign_id', sa.String(length=100), nullable=True))
    op.add_column('finding', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('finding', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('finding', 'title',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('finding', 'severity',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severityenum'),
               existing_nullable=True)
    op.create_foreign_key(None, 'finding', 'user', ['owner_id'], ['id'])
    op.drop_column('finding', 'url')
    op.create_index(op.f('ix_honeypot_instance_name'), 'honeypot_instance', ['name'], unique=True)
    op.create_index(op.f('ix_honeypot_log_attacker_ip'), 'honeypot_log', ['attacker_ip'], unique=False)
    op.create_index(op.f('ix_honeypot_log_honeypot_name'), 'honeypot_log', ['honeypot_name'], unique=False)
    op.alter_column('malwareanalysis', 'file_hash_sha256',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('malwareanalysis', 'yara_matches',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('malwareanalysis', 'static_features',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('malwareanalysis', 'risk_score',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('file_hash_sha256'), table_name='malwareanalysis')
    op.create_index(op.f('ix_malwareanalysis_file_hash_sha256'), 'malwareanalysis', ['file_hash_sha256'], unique=True)
    op.create_index(op.f('ix_malwareanalysis_id'), 'malwareanalysis', ['id'], unique=False)
    op.alter_column('scan', 'scan_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('scan', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='scanstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan', 'status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='scanstatus'),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('scan', 'scan_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_malwareanalysis_id'), table_name='malwareanalysis')
    op.drop_index(op.f('ix_malwareanalysis_file_hash_sha256'), table_name='malwareanalysis')
    op.create_index(op.f('file_hash_sha256'), 'malwareanalysis', ['file_hash_sha256'], unique=True)
    op.alter_column('malwareanalysis', 'risk_score',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('malwareanalysis', 'static_features',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('malwareanalysis', 'yara_matches',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('malwareanalysis', 'file_hash_sha256',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.drop_index(op.f('ix_honeypot_log_honeypot_name'), table_name='honeypot_log')
    op.drop_index(op.f('ix_honeypot_log_attacker_ip'), table_name='honeypot_log')
    op.drop_index(op.f('ix_honeypot_instance_name'), table_name='honeypot_instance')
    op.add_column('finding', sa.Column('url', mysql.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'finding', type_='foreignkey')
    op.alter_column('finding', 'severity',
               existing_type=sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severityenum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('finding', 'title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               nullable=True)
    op.drop_column('finding', 'updated_at')
    op.drop_column('finding', 'owner_id')
    op.drop_column('finding', 'campaign_id')
    op.drop_column('finding', 'references')
    op.drop_column('finding', 'remediation')
    op.drop_column('finding', 'cvss_score')
    op.drop_column('finding', 'cve_id')
    op.drop_column('finding', 'tool')
    op.drop_column('finding', 'target')
    op.drop_column('finding', 'status')
    op.create_table('malware_analysis',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('sha256', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('file_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('entropy', mysql.FLOAT(), nullable=True),
    sa.Column('risk_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_malware_analysis_id'), 'malware_analysis', ['id'], unique=False)
    op.drop_index(op.f('ix_compliance_mapping_id'), table_name='compliance_mapping')
    op.drop_table('compliance_mapping')
    op.drop_index(op.f('ix_se_campaign_id'), table_name='se_campaign')
    op.drop_table('se_campaign')
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_credential_id'), table_name='credential')
    op.drop_table('credential')
    op.drop_index(op.f('ix_payload_id'), table_name='payload')
    op.drop_table('payload')
    op.drop_index(op.f('ix_compliance_control_id'), table_name='compliance_control')
    op.drop_table('compliance_control')
    op.drop_index(op.f('ix_campaign_id'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_user_activity_id'), table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_team_member_id'), table_name='team_member')
    op.drop_table('team_member')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_compliance_framework_id'), table_name='compliance_framework')
    op.drop_table('compliance_framework')
    # ### end Alembic commands ###
